### ISSUE TITLE
Uncaught ReferenceError: nunt is not defined

### ISSUE THREAD

**Issue by fabiosantoscode** [camme/webhook-deployer#12]
The web UI gave me this error.

`node` also blurted this out, stating that the module "nunt" did not exist, but I was able to work around that by npm installing it.

I'm on a debian system, using node 0.10.25

**Comment by appsforartists** [comment]
I installed nunt, which makes the server code run.  The web UI is still broken.

**Comment by appsforartists** [comment]
I ran `npm install nunt`, which makes the server code run, but the web UI is still broken.

I think it is fixable by copying `nunt.js` to `public/js/`, adding a line to [index.html](https://github.com/camme/webhook-deployer/blob/master/public/views/index.html#L7), and modifying [webdep.js](https://github.com/camme/webhook-deployer/blob/master/lib/webdep.js#L70) to route requests to `/js/nunt.js` to `static.js`.

That's the same pattern @camme is using for mustache, but manually copying the dependency over from `node_modules` defeats the point of node.  It would be better to use something like webpack.

I'm also not seeing any feedback at all when I hit the `Deploy` button, so I don't know if it's working.  I'm having some issues with out Github Enterprise instance that are preventing me from testing with real githooks, so I'm of limited help right now.

@camme, is there a file missing or misconfigured in the public Github repo?  How are you passing `nunt.js` between the server and client in your deployment?

**Comment by camme** [comment]
Hi

I think I'll remove the nunt dependency all together. nunt serves its own file by using its middleware and routing calls to nunt.js. But I think its better if I remove it instead and use socket io directly (nunt is used to send events easier between frontend-frontend and frontend-server, which is a little overkill for something as small as webhook-deployer).

**Comment by camme** [comment]
It should be fixed now. No more nunt. Let me know if you still have problems!

**Comment by fabiosantoscode** [comment]
I will, thank you! And btw thanks for making this, it is very useful and
simple to use <3

**Comment by camme** [comment]
Thank you @fabiosantoscode for using it. It's much, much more fun to do something that others find useful...
