### ISSUE TITLE
wrong port

### ISSUE THREAD

**Issue by tartavull** [camme/webhook-deployer#8]
while running  'webhook-deployer --configfile /home/server/deploy.conf  --port 80'
I get 'Started webhook-deployer server app version 0.6.5 with port 8080
...'

**Comment by christianbundy** [comment]
:+1:

Using `"port": 80` in the config file doesn't do anything.

@camme can we get an update on this please? Thanks!

**Comment by camme** [comment]
@christianbundy @nevercast The issue shoude be solved now. If you use the --port option, it will use that instead of the port in the config file.
